require("Const")

--40 characters total
local PL = {
    {name = "Link", image = love.graphics.newImage("res/link.jpg")},
    {name = "John"},--, image = love.graphics.newImage("res/john.png")},
    {name = "Test"},
    {name = "alex"},
    {name = "alex"},
    {name = "alex"},
    {name = "alex"},
    {name = "alex"},
    {name = "alex"},
    {name = "alex"},
    {name = "alex"},
    {name = "alex"},
    {name = "alex"},
    {name = "alex"},
    {name = "alex"},
    {name = "alex"},
    {name = "alex"},
    {name = "alex"},
    {name = "alex"},
    {name = "alex"},
    {name = "alex"},
    {name = "alex"},
    {name = "alex"},
    {name = "alex"},
    {name = "alex"},
    {name = "alex"},
    {name = "alex"},
    {name = "alex"},
    {name = "alex"},
    {name = "alex"},
    {name = "alex"},
    {name = "alex"},
    {name = "alex"},
    {name = "alex"},
    {name = "alex"},
    {name = "alex"},
    {name = "alex"},
    {name = "alex"},
    {name = "alex"},
    {name = "alex"},
}

return PL