require("Const")

--40 characters total
local PL = {
    {name = "Link", image = love.graphics.newImage("res/link.jpg")},
    {name = "Metroid", image = love.graphics.newImage("res/metroid.jpg")},
    {name = "Test"},
    {name = "alex"},
    {name = "alex"},
    {name = "alex"},
    {name = "alex"},
    {name = "alex"},
    {name = "alex"},
    {name = "alex"},
    {name = "alex"},
    {name = "alex"},
    {name = "alex"},
    {name = "alex"},
    {name = "alex"},
    {name = "alex"},
    {name = "alex"},
    {name = "alex"},
    {name = "alex"},
    {name = "alex"},
    {name = "alex"},
    {name = "alex"},
    {name = "alex"},
    {name = "alex"},
    {name = "alex"},
    {name = "alex"},
    {name = "alex"},
    {name = "alex"},
    {name = "alex"},
    {name = "alex"},
    {name = "alex"},
    {name = "alex"},
    {name = "alex"},
    {name = "alex"},
    {name = "alex"},
    {name = "alex"},
    {name = "alex"},
    {name = "alex"},
    {name = "alex"},
    {name = "alex"},
}

return PL